name = "issa"
description = "a commenting server similar to Disqus"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT"
website = "https://github.com/reznikmm/issa"
tags = ["web", "servlet"]
project-files = ["gnat/issa.gpr"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
"*".ada_version = "Ada2022"

[[depends-on]]
matreshka_spikedog_api = "^21.0.0"
